apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  labels:
    app: eshop
data:
  web__ConnectionStrings__CatalogConnection: __CatalogConnection__
  web__ConnectionStrings__IdentityConnection: __IdentityConnection__