apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eshop
        component: web
    spec:
      containers:
        - name: web
          image: __REPOSITORY__/web:__ImageNumber__
          imagePullPolicy: Always
          env:
          - name: ConnectionStrings__CatalogConnection
            valueFrom:
              configMapKeyRef:
                name: externalcfg
                key: web__ConnectionStrings__CatalogConnection
          - name: ConnectionStrings__IdentityConnection
            valueFrom:
              configMapKeyRef:
                name: externalcfg
                key: web__ConnectionStrings__IdentityConnection
          - name: ApplicationInsights__InstrumentationKey
            valueFrom:
              configMapKeyRef:
                name: externalcfg
                key: web__ApplicationInsights__InstrumentationKey
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred